server:
    port: 2234
spring:
    cache:
        type: simple
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/treasure_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&&useSSL=false
        username: treasure_test
        password: Treasure@treasure
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
    redis:
        host: 127.0.0.1
        port: 6379
        timeout: 5000
        password: 
        jedis:
           pool.max-active: 8
           pool.max-wait: -1
           pool.max-idle: 8
           pool.min-idle: 0
    servlet:
        multipart:
           enabled: true
           file-size-threshold: 0
           max-file-size: 1Mb
           max-request-size: 10Mb
           file-path: /data/insurance-treasure/test/files/
           show: /f/
logging:
    level:
        root: INFO
        org.springframework.web: INFO
        org.hibernate: INFO
    file: ./log/log.log
sms:
    app:
        key: LTAIwHu0sqMlrOjl
        secret: HYD7y8YO2NIvp5KBH6acAZYbTSZQ5P
    template:
        code: SMS_149710018
cpic:
    web:
        wsdl.url: http://182.150.60.49/freight/zrxservices/FreightCommonService?wsdl
    userName: EBTEST
    password: Ecargo1234
    classescode: 11040200
    unitcode: 3110100
    