server:
    port: 4455
spring:
    cache:
        type: simple
    datasource:
        url: jdbc:mysql://192.168.3.7:4406/treasure_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&&useSSL=false
        username: root
        password: Root123!
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
    redis:
        host: 127.0.0.1
        port: 6379
        timeout: 5000
        password: admanageradmanager
        jedis:
           pool.max-active: 8
           pool.max-wait: -1
           pool.max-idle: 8
           pool.min-idle: 0
    servlet:
        multipart:
           enabled: true
           file-size-threshold: 0
           max-file-size: 100Mb
           max-request-size: 100Mb
           file-path: C:/home/workspace/
           show: /f/
logging:
    level:
        root: INFO
        org.springframework.web: INFO
        org.hibernate: INFO
    file: /home/kevin/temp/log/log.log
sms:
    app:
        key: LTAIwHu0sqMlrOjl
        secret: HYD7y8YO2NIvp5KBH6acAZYbTSZQ5P
    template:
        code: SMS_149710018
cpic:
    web:
        wsdl.url: http://182.150.60.64/freight/zrxservices/FreightCommonService?wsdl
    userName: EBTEST
    password: Ecargo1234
    classescode: 11040200
    unitcode: 3110100
    